<?
$htmldisrep=array("rob_text_id"=>"ID", 
"rob_nick"=>"Nick",
"rob_subject"=>"Subject",
"rob_privmsgs"=>"Message",
"rob_date"=>"Date",
"rob_time"=>"Time",
"rob_type"=>"Type",
"cust_id"=>"##",
"salutation"=>"Sal",
"family_name"=>"Family Name",
"first_name"=>"First Name",
"fullname"=>"Full Name",
"sex"=>"Sex",
"dietary"=>"Dietary",
"hotelcheckindate"=>"Hotel Check-In Date",
"hotelcheckoutdate"=>"Hotel Check-Out Date",
"pickuptime"=>"Departure Pick-Up Time",
"player_type"=>"Player Type",
"country_name"=>"Country",
"arrival_date"=>"Arrival Date",
"arrival_time"=>"Arrival Time",
"arrival_flight"=>"Arrival Flight",
"arrival_port"=>"Arrival Airport",
"depart_date"=>"Departure Date",
"depart_time"=>"Departure Time",
"depart_flight"=>"Departure Flight",
"depart_port"=>"Departure Airport",
"day_stay"=>"Hotel Stay",
"transport"=>"Transport Mode",
"transport2"=>"Transfer Requirement",
"comment"=>"Comment",
"room_name"=>"Full Room Name",
"room_short_form"=>"Room",
"cust_act_id"=>"A. ID",
"cust_act_date"=>"Activity Date",
"act_ref_id"=>"Activity Name",
"blacklist" => "Blacklist",
"cust_act_no"=>"Customer Number",
"handi_ref_id"=>"H. ID",
"cust_handi_id"=>"CH. ID",
"cust_handi_div"=>"Div",
"cust_initial_hcp"=>"Initial HCP",
"cust_adj_hcp"=>"Adj HCP",
"country_id"=>"Co. ID",
"room_id"=>"R. ID",
"room_description"=>"Description",
"short_form"=>"SFV",
"act_name"=>"Activity Name",
"act_description"=>"Activity Description",
"handi_name"=>"Event Name",
"handi_description"=>"Event Description",
"act_default"=>"Default Setting",
"act_date"=>"Activity Date",
"fid"=>"##",
"name"=>"File Name",
"filesize"=>"File Size",
"filetype"=>"File Type",
"staffid"=>"Staff Uploaded",
"entrydate"=>"Created On",
"lastmodified"=>"Modified On",
"tb_name"=>"Table Name",
"dlog_user"=>"User ID",
"dlog_time"=>"Edit on ",
"dlog_action"=>"Action",
"dlog_flag"=>"Changed",
"dlog_tb_id"=>"Record ID",
"dlog_reason"=>"Reason",


""=>"NIL"
);
//print_r($htmldisrep);

?>
